version: 0.1

phases:
  pre_build:
    commands:
      - echo Getting sparser core
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - aws s3 cp s3://bigmech/sparser_core/save-semantics.sh .
      - aws s3 cp s3://bigmech/sparser_core/r3.core .
      - aws s3 cp s3://bigmech/sparser_core/version.txt .
      - aws s3 cp s3://bigmech/reach-1.6.1-SNAPSHOT-FAT.jar .
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
